### ISSUE TITLE
Flutter web support?

### ISSUE THREAD

**Issue by CiriousJoker** [serenader2014/flutter_carousel_slider#61]
Anytime soon?

Until then, here is my fork with dependencies fixed.
I also removed the examples since they don't work anyway.

https://github.com/CiriousJoker/flutter_carousel_slider

**Comment by joelbrostrom** [comment]
What are you talking about?

What kind of _web support_ do you want?

**Comment by CiriousJoker** [comment]
Flutter is going to support the web platform eventually (Project Hummingbird) and it's currently in developer preview, but pretty usable.

It's mostly compatible already, but you have to change dependencies from flutter to flutter_web. flutter_web provides the same things as flutter, but is kept separate for now to speed up development. Later, flutter_web will be merged into flutter. Because of that, I asked if there will be a branch with the changed dependencies in the meantime.

**Comment by joelbrostrom** [comment]
Thank you for the explanation.

Good initiative to fork it.
I look forward to learning more about it!

**Comment by jdeltoft** [comment]
I +1 this initiative/request.  I have found other plugins not supported on flutter for web as well, such as https://pub.dev/packages/percent_indicator 

And it's very hard to debug from the error message.  See this flutter issue I raised. 

https://github.com/flutter/flutter/issues/44111

**Comment by jdeltoft** [comment]
Hi @CiriousJoker, I'm not sure how exactly to use your forked version.  I tried this:

```
dependencies:
  flutter:
    sdk: flutter
  #carousel_slider: ^1.3.0
  carousel_slider:
    git: https://github.com/jdeltoft/flutter_carousel_slider

```

But it fails with this error message:

```
Running "flutter pub get" in audacy_on_tap...                   
Because every version of carousel_slider from git depends on flutter_web_ui any which is forbidden, carousel_slider from git is forbidden.

So, because audacy_on_tap depends on carousel_slider from git, version solving failed.

pub get failed (server unavailable) -- attempting retry 1 in 1 second...
Because every version of carousel_slider from git depends on flutter_web_ui any which is forbidden, carousel_slider from git is forbidden.

So, because audacy_on_tap depends on carousel_slider from git, version solving failed.

```

**Comment by CiriousJoker** [comment]
@jdeltoft 

This thing is basically unmaintained until I need it again, but if you're lucky, it still works.

Here's how to use it (untested, copied from other project that uses a similar fork):
```
dependencies:
    expandable: any

dependency_overrides:
    expandable:
        git:
            url: https://github.com/CiriousJoker/flutter-expandable
```

**Comment by CiriousJoker** [comment]
@joelbrostrom 

Would be great if you could add this little fork as another branch (flutter_web or smth.), so that the fork isn't necessary and unmaintained.

**Comment by jdeltoft** [comment]
> @jdeltoft
> 
> This thing is basically unmaintained until I need it again, but if you're lucky, it still works.
> 
> Here's how to use it (untested, copied from other project that uses a similar fork):
> 
> ```
> dependencies:
>     expandable: any
> 
> dependency_overrides:
>     expandable:
>         git:
>             url: https://github.com/CiriousJoker/flutter-expandable
> ```

Ok, I think the error I'm getting is referring to your commit: 24b4be808701d42ea19cc7dd62d9ccaa31f461b4

where you changed the dependencies to:

dependencies:
  flutter_web: any

So maybe things have become more strict since you first forked off and built?

**Comment by CiriousJoker** [comment]
No, that's correct.

flutter_web is a drop in replacement for flutter.

Afaik, your error comes from

audacy_on_tap -> carousel_slider (official version from serenader) -> flutter

Should be:

audacy_on_tap -> carousel_slider (my fork) -> flutter_web

To tell flutter to use my fork, you have to override the dependencies like I showed you.
Does the error still persist?

**Comment by jdeltoft** [comment]
Here is my pubspec.yaml:

![image](https://user-images.githubusercontent.com/4506303/68173438-9ab42d80-ff40-11e9-9313-1f6913e80c88.png)

and it still gives the error.  I think I'm following your dependencies comment?

![image](https://user-images.githubusercontent.com/4506303/68173406-7c4e3200-ff40-11e9-9fe3-f4a5fbf8d87d.png)

**Comment by CiriousJoker** [comment]
Why do you have a dependency on flutter?
Flutter disables flutter web.

Here's the full example:

```

dependencies:
    flutter_web: any
    flutter_web_ui: any
    carousel_slider: any

dependency_overrides:
    flutter_web:
        git:
            url: https://github.com/flutter/flutter_web
            path: packages/flutter_web
    flutter_web_ui:
        git:
            url: https://github.com/flutter/flutter_web
            path: packages/flutter_web_ui
    expandable:
        git:
            url: https://github.com/CiriousJoker/carousel_slider
```
